code/reservation/urls.py
from django.urls import path

from . import views


app_name = 'reservation'
urlpatterns = [
    # e.g. /reservation/login
    path('', views.login, name='login'),
    # e.g. /reservation/logout
    path('logout/', views.logout, name='logout'),
    # e.g. /reservation/index
    path('index/', views.index, name='index'),
    # e.g. /reservation/room/1
    path('room/<int:room_id>/', views.room, name='room'),
    # e.g. /reservation/add_event/1
    path('add_event/<int:room_id>/', views.add_event, name='add_event'),
    # e.g. /reservation/update_event/
    path('update_event/', views.update_event, name='update_event'),
    # e.g. /reservation/delete_event
    path('delete_event/', views.delete_event, name='delete_event'),
]

code/room_reservation/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('reservation/', include('reservation.urls')),
    path('admin/', admin.site.urls),
]

code/reservation/models.py
from django.db import models
from django.utils.timezone import localtime

class Admin(models.Model):
    user_id = models.CharField(max_length=20)
    user_name = models.CharField(max_length=20)
    create_time = models.DateTimeField('create time', auto_now_add=True)
    last_update_time = models.DateTimeField('last update time', auto_now=True)

    def __str__(self):
        return f'{self.user_name} ({self.user_id})'

class Organization(models.Model):
    department_code = models.CharField(max_length=20)
    department_name = models.CharField(max_length=60)
    create_time = models.DateTimeField('create time', auto_now_add=True)
    last_update_time = models.DateTimeField('last update time', auto_now=True)

    def __str__(self):
        return f'{self.department_code} - {self.department_name}'

class Room(models.Model):
    room_name = models.CharField(max_length=30)
    room_department_code = models.CharField(max_length=20)
    room_department = models.CharField(max_length=60)
    manager_id = models.CharField(max_length=20)
    manager = models.CharField(max_length=20)
    create_time = models.DateTimeField('create time', auto_now_add=True)
    last_update_time = models.DateTimeField('last update time', auto_now=True)

    def __str__(self):
        return f'{self.room_department_code} - {self.room_name}'

class Reservation(models.Model):
    room_id = models.ForeignKey(Room, on_delete=models.CASCADE)
    meeting_name = models.CharField(max_length=60)
    borrower_id = models.CharField(max_length=20)
    borrower = models.CharField(max_length=20)
    borrower_department_code = models.CharField(max_length=20)
    begin_time = models.DateTimeField('begin time')
    end_time = models.DateTimeField('end time')
    create_time = models.DateTimeField('create time', auto_now_add=True)
    last_update_time = models.DateTimeField('last update time', auto_now=True)

    def date_to_string(self, date):
        local_date = localtime(date)
        return local_date.strftime('%Y-%m-%d (%a.)%H:%M:%S')

    def __str__(self):
        return f'{self.meeting_name}, {self.borrower_department_code} - {self.borrower} ({self.borrower_id}) 預約 {self.room_id} 從 {self.date_to_string(self.begin_time)} 到 {self.date_to_string(self.end_time)}'

code/reservation/views.py
from urllib import response
import requests
from datetime import datetime
from venv import create
from django.shortcuts import render
from django.http import JsonResponse, HttpResponseRedirect
from django.urls import reverse

from .models import Reservation, Room, Admin

import json


def login(request):
    """Login page
        (GET) - Display login page
        (POST) - User login from login form (API)
    """
    if request.method == 'POST':
        data = {
            'UserID': request.POST['userID'],
            'password': request.POST['password'],
            # 'remember': request.POST.get('remember') is not None
        }
        request.session['user_id'] = data['UserID']
        request.session['passwd'] = data['password']

        login_api = 'http://inlcnws/InxSSOAuth/api/Auth/CheckAD'
        response = requests.post(login_api, json=data)
        json_response = json.loads(response.text)
        print(json_response)

        if json_response['errMsg'] == '':
            user_properties = json.loads(json_response['Properties'])
            print(user_properties)
            request.session['user_id'] = user_properties['employeeid'][0]
            display_name = user_properties['displayname'][0]
            request.session['user_name'] = display_name.split(' ')[-1]
            request.session['user_dept'] = user_properties['department'][0]

            try:
                _ = Admin.objects.get(user_id=request.session['user_id'])
                request.session['is_admin'] = True
            except Admin.DoesNotExist:
                request.session['is_admin'] = False

            return HttpResponseRedirect(reverse('reservation:index'))
        else:
            msg = '登入失敗'
            return render(request, 'reservation/login.html', locals())
    else:
        if 'user_id' in request.session:
            return HttpResponseRedirect(reverse('reservation:index'))
        else:
            return render(request, 'reservation/login.html', locals())


def logout(request):
    """Logout (API)"""
    for key in list(request.session.keys()):
        del request.session[key]

    return HttpResponseRedirect(reverse('reservation:login'))


def index(request):
    """Display room list"""
    room_list = list(Room.objects.order_by('id'))
    context = {'room_list': room_list}
    return render(request, 'reservation/index.html', context)


def room(request, room_id):
    """Display reservation data of room with room_id"""
    try:
        print(type(request.session['is_admin']), request.session['is_admin'])
        if request.session['is_admin']:
            reservation_list = Reservation.objects.filter(room_id=room_id)
        else:
            reservation_list = Reservation.objects.filter(
                room_id=room_id, borrower_id=request.session['user_id'])
    except Reservation.DoesNotExist:
        reservation_list = []

    print(reservation_list)
    room_info = Room.objects.get(pk=room_id)
    context = dict()
    data = [{
        'id': elem.id,
        'borrower_id': elem.borrower_id,
        'borrower': elem.borrower,
        'borrower_department': elem.borrower_department_code,
        'meeting_name': elem.meeting_name,
        'begin_time': elem.begin_time.isoformat(),
        'end_time': elem.end_time.isoformat(),
    } for elem in reservation_list]

    context['reservation'] = json.dumps(data)
    context['room'] = room_info

    return render(request, 'reservation/room.html', context)


def add_event(request, room_id):
    """Add event data of room reservation (API)
    """
    is_ajax = request.headers.get('X-Requested-With') == 'XMLHttpRequest'

    if is_ajax:
        if request.method == 'POST':
            room = Room.objects.get(pk=room_id)
            data = json.loads(request.body)
            new_reservation = Reservation.objects.create(
                room_id=room,
                meeting_name=data['meeting_name'],
                borrower_id=data['borrower_id'],
                borrower=data['borrower'],
                borrower_department_code=data['borrower_department_code'],
                begin_time=data['begin_time'],
                end_time=data['end_time'],
            )
            new_reservation.save()
            result = {
                'reservation_id': new_reservation.id,
                'response': True,
            }
            return JsonResponse(result)
        else:
            result = {
                'reservation_id': None,
                'response': False,
            }
            return JsonResponse(result)


def update_event(request):
    """Update event data of room reservation (API)
    """
    is_ajax = request.headers.get('X-Requested-With') == 'XMLHttpRequest'

    if is_ajax:
        if request.method == 'POST':
            data = json.loads(request.body)
            reservation_id = data['id']
            reservation = Reservation.objects.get(pk=reservation_id)
            reservation.meeting_name = data['meeting_name']
            reservation.begin_time = data['begin_time']
            reservation.end_time = data['end_time']
            reservation.save()

            result = {
                'response': True,
            }
            return JsonResponse(result)
        else:
            result = {
                'response': False,
            }
            return JsonResponse(result)


def delete_event(request):
    """Delete event data of room reservation (API)
    """
    is_ajax = request.headers.get('X-Requested-With') == 'XMLHttpRequest'

    if is_ajax:
        if request.method == 'POST':
            data = json.loads(request.body)
            reservation_id = data['id']
            reservation = Reservation.objects.get(pk=reservation_id)
            reservation.delete()

            result = {
                'response': True,
            }
            return JsonResponse(result)
        else:
            result = {
                'response': False,
            }
            return JsonResponse(result)

code/reservation/templates/reservation/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>會議室預約系統</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'reservation/bootstrap/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'reservation/bootstrap-icon/bootstrap-icons.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'reservation/custom.css' %}">
</head>

<body>
    <div class="container">
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container-fluid">
                <a class="navbar-brand" href="#"><i class="bi-calendar-event"
                        style="font-size: 1.25rem; color: rgb(255, 255, 255);"></i> 會議室預約系統</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false"
                    aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                    <div class="navbar-nav">
                        <a class="nav-link" aria-current="page" href="{% url 'reservation:index' %}">會議室清單</a>
                    </div>
                </div>
                <div class="d-flex">
                    <span class="navbar-text me-2">
                        {{ request.session.user_name }}({{ request.session.user_id }})
                    </span>
                    <a class="btn btn-warning" href="{% url 'reservation:logout' %}">Logout</a>
                </div>
            </div>
        </nav>
        <div class="row text-center">
            <div class="col my-5">
                {% if room_list %}
                <div class="col list-group">
                    {% for room in room_list %}
                    <a href="{% url 'reservation:room' room.id %}" class="list-group-item list-group-item-action">
                        {{room.room_department_code}} - {{ room.room_name }}
                    </a>
                    {% endfor %}
                </div>
                {% else %}
                <h2>沒有可借的會議室</h2>
                {% endif %}
            </div>
        </div>
    </div>
    <script src="{% static 'reservation/bootstrap/bootstrap.bundle.min.js' %}"></script>
</body>

</html>

code/reservation/templates/reservation/login.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>會議室預約系統</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'reservation/bootstrap/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'reservation/custom.css' %}">
</head>

<body>
    <main class="form-signin text-center mt-5">
        <form id="loginForm" action="{% url 'reservation:login' %}" method="post">
            {% csrf_token %}
            <h1 class="h3 mb-3 fw-normal">請登入</h1>
            <div class="form-floating mb-3">
                <input type="text" name="userID" class="form-control" id="user">
                <label for="user">帳號</label>
            </div>
            <div class="form-floating mb-3">
                <input type="password" name="password" class="form-control" id="passwd">
                <label for="passwd">密碼</label>
            </div>
            <div class="checkbox mb-3">
                <label>
                    <input name="remember" type="checkbox" value="yes"> 記住我
                </label>
                <input type="hidden" name="ff" id="" value="{{ request.session.msg }}">
            </div>
            <button class="w-100 btn btn-lg btn-primary" type="submit">登入</button>
            {% if msg %}
            <p class="mt-3 text-danger">{{ msg }}</p>
            {% endif %}
            <p class="mt-5 mb-3 text-muted">© 2022</p>
        </form>
    </main>
    <script src="{% static 'reservation/bootstrap/bootstrap.bundle.min.js' %}"></script>
</body>

</html>

code/reservation/templates/reservation/room.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>會議室預約系統</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'reservation/bootstrap/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'reservation/bootstrap-icon/bootstrap-icons.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'reservation/tempus-dominus/tempus-dominus.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'reservation/fullcalendar/main.min.css' %}">
</head>

<body>
    <div class="container">
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container-fluid">
                <a class="navbar-brand" href="#"><i class="bi-calendar-event"
                        style="font-size: 1.25rem; color: rgb(255, 255, 255);"></i> 會議室預約系統</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false"
                    aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                    <div class="navbar-nav">
                        <a class="nav-link" aria-current="page" href="{% url 'reservation:index' %}">會議室清單</a>
                    </div>
                </div>
            </div>
        </nav>
        <div class="row">
            <h1 id="roomData" class="text-center" data-json="{{ room }}">{{ room }}</h1>
            <dev class="col">
                <div id="calendar"></div>
                <div style="display: none" id="jsonData" data-json="{{ reservation }}"></div>
                <div style="display: none" id="user_id" data-json="{{ request.session.user_id }}"></div>
                <div style="display: none" id="user_name" data-json="{{ request.session.user_name }}"></div>
                <div style="display: none" id="user_dept" data-json="{{ request.session.user_dept }}"></div>
            </dev>
        </div>
        <div class="modal fade" id="eventModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1"
            aria-labelledby="eventModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="eventModalLabel">預約資訊</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        <form>
                            <div class="mb-3 input-group">
                                <label for="name" class="input-group-text">預約者</label>
                                <input type="text" class="form-control" id="name" readonly>
                            </div>
                            <div class="mb-3 input-group">
                                <label for="room" class="input-group-text">會議室</label>
                                <input type="text" class="form-control" id="room" readonly>
                            </div>
                            <div class="mb-3 input-group">
                                <label for="purpose" class="input-group-text">用途</label>
                                <input type="text" class="form-control" id="purpose">
                            </div>
                            <div class="mb-3 input-group" id='startDatetimepicker' data-td-target-input='nearest'
                                data-td-target-toggle='nearest'>
                                <label class="input-group-text" for="start-time">開始時間</label>
                                <input id='start-time' type='text' class='form-control'
                                    data-td-target='#startDatetimepicker' />
                                <span class='input-group-text' data-td-target='#startDatetimepicker'
                                    data-td-toggle='datetimepicker'>
                                    <i class="bi-calendar" style="font-size: 1rem; color: rgb(0, 0, 0);"></i>
                                </span>
                            </div>
                            <div class="mb-3 input-group" id='endDatetimepicker' data-td-target-input='nearest'
                                data-td-target-toggle='nearest'>
                                <label for="end-time" class="input-group-text">結束時間</label>
                                <input id='end-time' type='text' class='form-control'
                                    data-td-target='#endDatetimepicker' />
                                <span class='input-group-text' data-td-target='#endDatetimepicker'
                                    data-td-toggle='datetimepicker'>
                                    <i class="bi-calendar" style="font-size: 1rem; color: rgb(0, 0, 0);"></i>
                                </span>
                            </div>
                        </form>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">取消</button>
                        <button type="button" id="btnAdd" class="btn btn-primary"
                            data-url="{% url 'reservation:add_event' room.id %}"
                            data-token="{{ csrf_token }}">確定</button>
                    </div>
                </div>
            </div>
        </div>
        <div class="modal fade" id="editModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1"
            aria-labelledby="editModal" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="editModalLabel">預約資訊</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        <form>
                            <input type="hidden" id="eventId" value="">
                            <div class="mb-3 input-group">
                                <label for="edit-name" class="input-group-text">預約者</label>
                                <input type="text" class="form-control" id="edit-name" readonly>
                            </div>
                            <div class="mb-3 input-group">
                                <label for="edit-room" class="input-group-text">會議室</label>
                                <input type="text" class="form-control" id="edit-room" readonly>
                            </div>
                            <div class="mb-3 input-group">
                                <label for="edit-purpose" class="input-group-text">用途</label>
                                <input type="text" class="form-control" id="edit-purpose">
                            </div>
                            <div class="mb-3 input-group" id='edit-startDatetimepicker' data-td-target-input='nearest'
                                data-td-target-toggle='nearest'>
                                <label class="input-group-text" for="start-time">開始時間</label>
                                <input id='edit-start-time' type='text' class='form-control'
                                    data-td-target='#edit-startDatetimepicker' />
                                <span class='input-group-text' data-td-target='#edit-sstartDatetimepicker'
                                    data-td-toggle='datetimepicker'>
                                    <i class="bi-calendar" style="font-size: 1rem; color: rgb(0, 0, 0);"></i>
                                </span>
                            </div>
                            <div class="mb-3 input-group" id='edit-endDatetimepicker' data-td-target-input='nearest'
                                data-td-target-toggle='nearest'>
                                <label for="end-time" class="input-group-text">結束時間</label>
                                <input id='edit-end-time' type='text' class='form-control'
                                    data-td-target='#edit-endDatetimepicker' />
                                <span class='input-group-text' data-td-target='#edit-endDatetimepicker'
                                    data-td-toggle='datetimepicker'>
                                    <i class="bi-calendar" style="font-size: 1rem; color: rgb(0, 0, 0);"></i>
                                </span>
                            </div>
                        </form>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">取消</button>
                        <button type="button" id="btnDelete" class="btn btn-danger"
                            data-url="{% url 'reservation:delete_event' %}" data-token="{{ csrf_token }}"><i
                                class="bi-trash" style="font-size: 1rem; color: rgb(255, 255, 255);"></i> 刪除</button>
                        <button type="button" id="btnUpdate" class="btn btn-primary"
                            data-url="{% url 'reservation:update_event' %}" data-token="{{ csrf_token }}"><i
                                class=" bi-check" style="font-size: 1rem; color: rgb(255, 255, 255);"></i> 更新</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script src="{% static 'reservation/popper/popper.min.js' %}"></script>
    <script src="{% static 'reservation/bootstrap/bootstrap.min.js' %}"></script>
    <script src="{% static 'reservation/fullcalendar/main.min.js' %}"></script>
    <script src="{% static 'reservation/tempus-dominus/tempus-dominus.js' %}"></script>
    <script src="{% static 'reservation/room.js' %}"></script>
</body>

</html>